package integration

import (
	"os"
	"os/exec"
	"strings"
	"testing"
)

const codemapPath = "../../docs/codemap.md"

const codemapHeader = `# Code map

Every Go package in the repo with the first sentence of its doc comment. Generated by ` + "`make codemap`" + `; edit the
package's ` + "`// Package ...`" + ` comment, never this file. ` + "`go doc ./<path>`" + ` prints the full comment.

`

// TestCodemapFresh keeps docs/codemap.md, the agent-facing package map CONTRIBUTING.md routes to, in step with the code:
// it fails when a package with non-test Go files has no doc comment, or when the committed map differs from the one
// `go list` produces now. COX_UPDATE_CODEMAP=1 (what `make codemap` sets) rewrites the file instead of comparing.
func TestCodemapFresh(t *testing.T) {
	cmd := exec.Command("go", "list", "-f", "{{if .GoFiles}}{{.ImportPath}}\t{{.Doc}}{{end}}", "./...")
	cmd.Dir = "../.."
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("go list: %v", err)
	}
	var b strings.Builder
	b.WriteString(codemapHeader)
	for _, ln := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		path, doc, _ := strings.Cut(ln, "\t")
		path = strings.TrimPrefix(path, "github.com/nphattai/coxswain/")
		if doc == "" {
			t.Errorf("package %s has no doc comment; add `// Package ...` above its package clause", path)
			continue
		}
		doc = strings.NewReplacer("<", "&lt;", ">", "&gt;").Replace(doc)
		b.WriteString("- `" + path + "` - " + doc + "\n")
	}
	want := b.String()

	if os.Getenv("COX_UPDATE_CODEMAP") == "1" {
		if err := os.WriteFile(codemapPath, []byte(want), 0o644); err != nil {
			t.Fatalf("write codemap: %v", err)
		}
		return
	}
	got, err := os.ReadFile(codemapPath)
	if err != nil {
		t.Fatalf("read codemap: %v (run make codemap)", err)
	}
	if string(got) != want {
		t.Errorf("docs/codemap.md is stale; run make codemap and commit the result")
	}
}
